// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Carousel from 'stimulus-carousel'

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MainController from "./main_controller"
application.register("main", MainController)

application.register('carousel', Carousel)
